# GitLab CI configuration to build PDFs from LaTeX sources and Diffs of these.
# (c) Farhad Mehta 2021

image: registry.gitlab.com/islandoftex/images/texlive:latest
# Tested with the TeX Live 2021 snapshot as of 09.12.2021
# Docker image: registry.gitlab.com/islandoftex/images/texlive:TL2021-2021-12-05-04-05

.latex-before_script: &latex-before_script
  - tlmgr --version
  - git --version
  - latex --version
  - latexmk --version
  # Note: it seems that `latexdiff --version` returns SIG(127) as an error code. Therefore use `|| true` to ignore this.
  - latexdiff --version || true
  # Check the current output from git-describe that may be added to the document
  - git describe --exclude "latexdiff" --always --long --dirty --broken

stages:
  - build
  - diff
  - deploy

build_doc:
  stage: build
  before_script:
    *latex-before_script
  script:
    - cd Documentation
    - make doc
    - cd ..
  artifacts:
    paths:
      - Documentation/out/*.pdf

build_doc_diff:
  stage: diff
  before_script:
    *latex-before_script
  when: manual
  needs:
    - "build_doc"
  script:
    - cd Documentation
    - make doc_diff
    - cd ..
  artifacts:
    paths:
      - Documentation/out/*.pdf

build_proposal:
  stage: build
  before_script:
    *latex-before_script
  when: manual
  script:
    - cd Documentation
    - make proposal
    - cd ..
  artifacts:
    paths:
      - Documentation/out/*.pdf

# The following job duplicates the functionality of the previous ones, just in case one in confident that everything works and would like to build everything in one job to save time and resources
build_proposal_doc_diff:
  stage: diff
  before_script:
    *latex-before_script
  when: manual
  script:
    - cd Documentation
    - make proposal
    - make doc
    - make doc_diff
    - cd ..
  artifacts:
    paths:
      - Documentation/out/*.pdf

deploy_cluster_job:
  stage: deploy
  needs: []
  image:
    name: bitnami/kubectl:1.22.7
    entrypoint: [""]
  environment:
    name: test
    url: https://10.20.1.29:6443
  script:
    - kubectl config get-contexts
    - kubectl config use-context SEProj/2022-FS/g03-kubewatch/kubewatch:ins-cluster-agent
    - kubectl get pods
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Documentation/**/*
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
