apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: nodejs-kubewatch
    context: .
    sync:
      infer:
      - '**/*'
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
