apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubewatch
    tier: db
  name: kubewatch-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: kubewatch
    tier: db
