# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: node-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewatch
  template:
    metadata:
      labels:
        app: kubewatch
    spec:
      containers:
        - name: server
          image: kubewatch
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DB_CONN_STRING
              value: "mongodb://kubewatch-mongodb:27017/kubewatch"
            - name: PROMETHEUS_CONN_STRING
              value: "http://prometheus.monitoring:9090"
